### ISSUE TITLE
Undefined symbol `yarp::dev::PolyDriver::closeMain()` while linking staticstep

### ISSUE THREAD

**Issue by darula-hpp** [roboticslab-uc3m/gaitcontrol#1]
Code just compiled fine. When I run the staticstep executable, I get `undefined symbol: _ZN4yarp3dev10PolyDriver9closeMainEv`
Which I thought meant that the `<yarp/dev/PolyDriver.h>`  was not included. I included it in the `staticstep.cpp`. After I compile, It compiles successfully but after I run the program, I get the same error

**Comment by PeterBowman** [comment]
Which version of YARP are you compiling/linking against? The symbol seems to be (after demangling) `yarp::dev::PolyDriver::closeMain()`, which was removed a couple of years ago (last present at [yarp-3.0](https://github.com/robotology/yarp/blob/30dce540494b8cda5d9d40018384c047a8b47fe6/src/libYARP_dev/include/yarp/dev/PolyDriver.h#L164), current stable branch is yarp-3.4).

Please uninstall YARP and make sure there are no leftover files/symlinks at `<install_prefix>/lib/libYARP_*` (the default prefix is `/usr/local`), otherwise remove them manually. Then, install YARP and build gaitcontrol again. You can make sure the linker is picking the correct .so files with a `ldd staticstep`.

**Comment by darula-hpp** [comment]
Hello @PeterBowman, I just installed `yarp-3.0`  and recompile gaitcontrol. The program runs just fine now. Also I was using `yarp-3.4`. 

Thank you
